all:
  vars:
    ansible_connection: ssh
    ansible_user: pi
    ansible_ssh_pass: raspberry
    ansible_become: true
    ansible_become_user: root
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    pi1:
      ansible_host: raspberrypi.local
        
